# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(nombres: "Andrés", apellido_paterno: 'Luna', username: 'andres', password:'andres', password_confirmation:'andres', email: 'che.de.la.luna@gmail.com', admin: true)
User.create!(nombres: "Carlos", apellido_paterno: 'Iñiguez', username: 'carlos', password:'carlos', password_confirmation:'carlos', email: 'carlosiniguez6@gmail.com', admin: true)
User.create!(nombres: "Alberto", apellido_paterno: 'Lima', username: 'beto', password:'beto123', password_confirmation:'beto123', email: 'betico19087@gmail.com', admin: true)
User.create!(nombres: "Fabricio", apellido_paterno: 'Flores', username: 'fabricio', password:'fabricio', password_confirmation:'fabricio', email: 'fabrifloresg@gmail.com', admin: true)
User.create!(nombres: "Mario", apellido_paterno: 'Correa', username: 'macool', password:'macool', password_confirmation:'macool', email: 'a@macool.me', admin: true)

Course.create(nombre:"Tiny Kids 3")
Course.create(nombre:"Tiny Kids 4")
Course.create(nombre:"Tiny Kids 5")
Course.create(nombre:"Tiny Kids 6")
Course.create(nombre:"Tiny Kids 7")
Course.create(nombre:"Tiny Kids 8")
Course.create(nombre:"Children 1")
Course.create(nombre:"Children 2")
Course.create(nombre:"Children 3")
Course.create(nombre:"Children 4")
Course.create(nombre:"Children 5")
Course.create(nombre:"Children 6")
Course.create(nombre:"Children 7")
Course.create(nombre:"Children 8")
Course.create(nombre:"Teens 1")
Course.create(nombre:"Teens 2")
Course.create(nombre:"Teens 3")
Course.create(nombre:"Teens 4")
Course.create(nombre:"Teens 5")
Course.create(nombre:"Teens 6")
Course.create(nombre:"Teens 7")
Course.create(nombre:"Teens 8")
Course.create(nombre:"Youth Intensive 1")
Course.create(nombre:"Youth Intensive 2")
Course.create(nombre:"Youth Intensive 3")
Course.create(nombre:"Youth Intensive 4")
Course.create(nombre:"Seniors 1")
Course.create(nombre:"Seniors 2")